#!/usr/bin/python3
import subprocess
import argparse
import requests
import re
from cmp_version import VersionString


APIURL = "https://api.opensuse.org"
MAINPROJECT = "openSUSE:Factory"
###

OSC_CMD = ['osc', '--apiurl', APIURL]

REPOLOGY_APIURL = 'https://repology.org/api/v1/project/'


def exec_process(cmdline: list[str]):
    return subprocess.Popen(
        cmdline, stdout=subprocess.PIPE, 
        stderr=subprocess.PIPE, encoding='utf8')

 
def get_last_changes(package: str):
    try:
        proc = exec_process(
            OSC_CMD+["ls", "-l", f"{MAINPROJECT}/{package}"])
        for line in proc.stdout.readlines():
            if f"{package}.changes" not in line:
                continue
            return line.split()[3:6]
    except:
        return []


def is_numeric(version: str) -> bool:
    return re.search(r"^\d+", version)


def get_obs_version(package: str) -> str:
    try:
        proc = exec_process(
            OSC_CMD+["cat", f"{MAINPROJECT}/{package}/{package}.spec"]
        )
        for line in proc.stdout.readlines():
            if "Version:" in line:
                version = line.split()[1]
                break
        if is_numeric(version):
            return version
        return ""
    except Exception as e:
        print(f"Error in getting version from OBS: {e}")
        return ""


def filter_repo(items: list[dict], refversion: str) -> list[dict]:
    # uses some heuristic to create a list of only entries with a newer version
    # on any parsing issue, returns the original list
    try:
        refv = VersionString(refversion)
        return list(filter(lambda x: refv < VersionString(x['version']), items))
    except ValueError:
        return items


def is_newer_on_repology(package: str, refversion: str) -> int:
    try:
        response = requests.get(f"{REPOLOGY_APIURL}/{package}",timeout=30)
        results = [r for r in response.json() if r['status'] ==
                   'newest' and r['version'] != refversion]
        # if the version is numeric, try to compare and filter out the one lesser
        if is_numeric(refversion):
            results = filter_repo(results, refversion)
        return len(results)
    except requests.exceptions.RequestException as e:
        return f"Sorry, we could not establish a connection to repology.org. Please make sure that you are connected to the internet and try again"


def main():
    parser = argparse.ArgumentParser(
        prog='last update',
        description='tells you when a package was last updated',
    )
    parser.add_argument(
        'package', help='the package name to check (ex bash, vim ...)')
    args = parser.parse_args()
    outputStr = f"- {args.package} "
    obs_version = get_obs_version(args.package)
    changes = get_last_changes(args.package)
    if not changes:
        outputStr += "Error in getting information. Does this package exist in Factory ?"
    else:
        outputStr += f"last version on {MAINPROJECT} is {obs_version} changed on {' '.join(changes)}"
    repo_with_new_packages = is_newer_on_repology(args.package, obs_version)
    if is_numeric(obs_version) and repo_with_new_packages:
        outputStr += f"\n  Other {repo_with_new_packages} repos may have newer versions, consider updating!"
    return outputStr


print(main())
