#!/usr/bin/python3
import subprocess
import argparse
import requests
import re

APIURL = "https://api.opensuse.org"
MAINPROJECT = "openSUSE:Factory"
###

OSC_CMD = ['osc', '--apiurl', APIURL]

REPOLOGY_APIURL = 'https://repology.org/api/v1/project/'


def exec_process(cmdline):
    return subprocess.Popen(cmdline, stdout=subprocess.PIPE, stderr=subprocess.PIPE, encoding='utf8')


def get_last_changes(package):
    try:
        proc = exec_process(
            OSC_CMD+["ls", "-l", f"{MAINPROJECT}/{package}"])
        for line in proc.stdout.readlines():
            if f"{package}.changes" not in line:
                continue
            return line.split()[3:6]
    except:
        return []


def is_numeric(version: str) -> bool:
    return re.search(r"^\d+", version)


def get_obs_version(package):
    try:
        proc = exec_process(
            OSC_CMD+["cat", f"{MAINPROJECT}/{package}/{package}.spec"]
        )
        for line in proc.stdout.readlines():
            if "Version:" in line:
                version = line.split()[1]
                break
        if is_numeric(version):
            return version
        else:
            return ""
    except:
        return ""


def is_newer_on_repology(package, refversion):
    try:
        response = requests.get(f"{REPOLOGY_APIURL}/{package}")
        return [r for r in response.json() if r['status'] == 'newest' and r['version'] != refversion]
    except:
        return None


def main():
    parser = argparse.ArgumentParser(
        prog='last update',
        description='tells you when a package was last updated',
    )
    parser.add_argument(
        'package', help='the package name to check (ex bash, vim ...)')
    args = parser.parse_args()
    obs_version = get_obs_version(args.package)
    changes = get_last_changes(args.package)
    if not changes:
        print("Error in getting information. Does this package exist?")
        return
    print(args.package, "last version on", MAINPROJECT,
          "is", obs_version, "changed on", ' '.join(changes))
    if is_numeric(obs_version) and is_newer_on_repology(args.package, obs_version):
        print("Other repos may have newer versions, consider updating!")


main()
